#!/usr/bin/env ansible-playbook

# user must be created before this is run

---
- hosts: all 
  gather_facts: no
  vars:
    update_cache: no
    authorized_ssh_users: ['cbergeron','pi']
  sudo: yes
  roles:
    - ssh-keys