#!/usr/bin/env ansible-playbook
---
- hosts: zeros 
  gather_facts: yes
  sudo: yes

  tasks:
    - name: TASK | Add Adafruit repo
      command: "/bin/bash -c 'curl -sLS https://apt.adafruit.com/add | sudo bash'"
      tags: always

    - name: TASK | Apt-get update
      command: "sudo apt-get update"
      tags: always

    - name: TASK | Apt-get upgrade (with tag_upgrade=true)
      command: "sudo apt-get update"
      tags: tag_upgrade

  handlers:
    - name: reboot
      command: shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
      register: restarted
