#!/usr/bin/env ansible-playbook
---
- hosts: all 
  gather_facts: yes
  vars:
    update_cache: no
  sudo: yes

  tasks:
    - name: TASK | Apt-get update 
      command: "sudo apt-get update"
      when:
        - ansible_ssh_host != 'gpserver'

  handlers:
    - name: reboot
      command: shutdown -r now
      ignore_errors: true
      register: restarted
