#!/usr/bin/env ansible-playbook
---
- hosts: all 
  gather_facts: yes
  vars:
    packages_to_install: [ git, automake, build-essential, 
        ipython, mosh, node, npm, python-pip, ruby-dev, python-dev,
        vim, cowsay, htop, ranger, iftop, dnsutils, lrzsz
        ]
    npm_packages_to_install: [ mqtt, crypto-js, minimist, websocket-stream ]
    update_cache: no
  sudo: yes

  tasks:
    - name: TASK | Set /etc/hostname
      template: src=templates/hostname.j2 dest=/etc/hostname
      tags: all
      notify:
        - reboot

    - name: TASK | Update /etc/hosts
      template: src=templates/hosts.j2 dest=/etc/hosts
      tags: all
      notify:
        - reboot

    - name: TASK | Update network/interfaces config so wifi starts on boot
      template: src=templates/interfaces.j2 dest=/etc/network/interfaces
      tags: all
    
    - name: TASK | Put wifi config in place
      template: src=templates/wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf
      tags: all
      notify:
        - reboot

    - name: TASK | Generate locale
      locale_gen: name=en_US.UTF-8 state=present
      tags: all

    - name: TASK | Set keyboard layout to US
      template: src=templates/keyboard.j2 dest=/etc/default/keyboard
      tags: all
      notify:
        - reboot
 
    #- name: TASK | Set CAPSLOCK to CTRL
    #  command: setxkbmap -option ctrl:nocaps

    - name: TASK | Update Timezone to Etc/UTC
      copy:
        content="Etc/UTC\n"
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
      tags: all
      notify:
        - update timezone

    - name: TASK | Create user(s)
      user:
        name: "{{ username }}"
        comment: 'Chris Bergeron'
        shell: /bin/bash
        groups: pi
        password: "{{ CBPASSWORDNEW }}"
      tags: all

    - name: TASK | Copy .bash_logout and .bash_logout files for user {{ username }}
      template: src="templates/bashrc.j2" dest="/home/{{ username }}/.bashrc"
      template: src="templates/bash_logout.j2" dest="/home/{{ username }}/.bash_logout"
      tags: all

    - name: TASK | Copy .bash_logout and bashrc for user pi
      template: src="templates/bashrc.j2" dest="/home/pi/.bashrc"
      template: src="templates/bash_logout.j2" dest="/home/pi/.bash_logout"
      tags: all

    - name: TASK | Set MOTD
      template: src=templates/motd.j2 dest=/etc/motd
      tags: all
 
    - name: TASK | Create mount directory for Pi files
      file:
        path: /mnt/pi
        state: directory
        mode: 0755
      tags: all

    - name: TASK | Update fstab to mount NAS volume to '/mnt/pi'
      template: src=templates/fstab.j2 dest=/etc/fstab
      notify:
        - reboot
      tags: all

    - name: TASK | Install python-apt (tag firstrun)
      command: apt-get install python-apt
      register: aptget
      changed_when: "'python-apt is already the newest version.' not in aptget.stdout_lines"
      tags: firstrun

    - name: TASK | Add Adafruit repo (tag firstrun)
      # command: "echo 'deb http://apt.adafruit.com/raspbian/ jessie main' | sudo tee --append /etc/apt/sources.list"
      # command: "wget -O - -q https://apt.adafruit.com/apt.adafruit.com.gpg.key | sudo apt-key add -"
      command: "/bin/bash -c 'curl -sLS https://apt.adafruit.com/add | sudo bash'"
      tags: firstrun 

    - name: TASK | Apt-get update (tag firstrun)
      command: "sudo apt-get update"
      tags: firstrun

    - name: TASK | Apt-get upgrade (tag firstrun)
      command: "sudo apt-get upgrade"
      tags: firstrun

    - name: TASK | Install packages (tag firstrun)
      apt: pkg={{ item }} state=installed update_cache={{ update_cache }}
      with_items: packages_to_install
      tags: firstrun

    - name: TASK | Install node.js packages with npm (tag firstrun)
      npm: name={{ item }} global=yes
      with_items: npm_packages_to_install
      tags: firstrun

  handlers:
    - name: reboot
      command: shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
      register: restarted