---
- hosts: all
  gather_facts: yes
  vars:
    reboot: "false"
  sudo: yes

  tasks:
    - name: TASK | Set /etc/hostname
      template: src=templates/hostname.j2 dest=/etc/hostname force=yes

    - name: TASK | Update /etc/hosts
      template: src=templates/hosts.j2 dest=/etc/hosts force=yes

    # set MOTD
    - name: TASK | Set MOTD
      shell: "(/usr/bin/toilet -w 120 -f mono12 -F metal `cat /etc/hostname` > /etc/motd)"

    - name: TASK | Reboot nodes (reboot=true)
      command: /sbin/reboot
      when: reboot | match("true")
