---
- name: TASK | Install xinetd
  apt: 
    name: xinetd
    state: present 
    update_cache: yes

- name: TASK | Install CheckMK Agent
  apt: 
    name: check-mk-agent
    state: present 
    update_cache: yes

#- name: TASK | Install CheckMK Agent and xinetd
  #apt: 
  #  name: "{{ item }}"
  #  state: present 
  #  update_cache: yes
  #  with_items:
  #    - xinetd
  #    - check-mk-agent

- name: TASK | Copy CheckMK Agent config
  template: src=check_mk dest=/etc/xinetd.d/check_mk
  notify: restart_xinetd

