---
- name: TASK | Copy Checkmk Agent
  template: src=check_mk_agent dest=/usr/bin/check_mk_agent mode=0755

- name: TASK | Copy Checkmk Agent Listener
  template: 
    src: checkmk_agent_listener
    dest: /usr/local/bin
    mode: 0755

- name: TASK | Create /etc/check_mk directory
  file: path=/etc/check_mk state=directory

- name: TASK | Copy mrpe.cfg
  template: 
    src: mrpe.cfg.j2
    dest: /etc/check_mk/mrpe.cfg
    mode: 0755

- name: TASK | Create Checkmk Agent Unit
  template:
    src: checkmk_agent.service.j2 
    dest: /lib/systemd/system/checkmk_agent.service
    mode: 0644
    owner: root
    group: root

- name: TASK | Start Checkmk Agent (and enable)
  service: name=checkmk_agent state=started enabled=yes

# Add host	
# curl 'http://${omd}/${site}/check_mk/webapi.py?action=add_host&_username=${user}&_secret=${$secret}' -d 'request={\"attributes\":{\"alias\": \"Alias of ${::fqdn}\", \"tag_agent\": \"cmk-agent\", \"tag_criticality\": \"${tag_criticality}\", \"ipaddress\": \"$ipaddress\"}, \"hostname\": \"${hostname}\", \"folder\": \"${folder}\"}'"
- name: TASK | Register host(s) with Checkmk
  uri:
    url: http://192.168.0.153/monitoring/check_mk/webapi.py?action=add_host&_username=grafana&_secret=UMKCXHTELTFCHEHAULOV
    method: GET
    body: "request={\"attributes\":{\"alias\": \"Alias of ${::fqdn}\", \"tag_agent\": \"cmk-agent\", \"tag_criticality\": \"production\", \"ipaddress\": \"$ipaddress\"}, \"hostname\": \"${hostname}\"}"
    #, \"folder\": \"${folder}\"}'"
    body_format: json
    HEADER_Content-Type: "application/json"
  when: registeragent | match("true")

# Discover services
# curl 'http://${omd}/${site}/check_mk/webapi.py?action=discover_services&_username=${user}&_secret=${$secret}' -d 'request={\"hostname\": \"${hostname}\"}'"
- name: TASK | Discover host services ${hostname}
  uri:
    url: http://192.168.0.153/monitoring/check_mk/webapi.py?action=discover_services&_username=grafana&_secret=UMKCXHTELTFCHEHAULOV
    method: GET
    body: "request={\"hostname\": \"${hostname}\"}"
    body_format: json
    HEADER_Content-Type: "application/json"
  when: registeragent | match("true")
    
# Activate changes
# curl 'http://${omd}/${site}/check_mk/webapi.py?action=activate_changes&_username=${user}&_secret=${$secret}'"
- name: TASK | Activate changes in Checkmk
  uri:
    url: http://192.168.0.153/monitoring/check_mk/webapi.py?action=activate_changes&_username=grafana&_secret=UMKCXHTELTFCHEHAULOV
    method: GET
    #body: "{{ lookup('file','mesos-consul.json') }}"
    #body_format: json
    HEADER_Content-Type: "application/json"
  when: registeragent | match("true")
